### ISSUE TITLE
No connection

### ISSUE THREAD

**Issue by Original-Tasty** [OLBITX/OLBITX#1]
HI, there is no connection to the walletbuilders' nodes.  Do you guys have any other connected node online?

**Comment by OLBITX** [comment]
Workaround is in place.

**Comment by OLBITX** [comment]
Please close if you feel your concern is addressed.

**Comment by Original-Tasty** [comment]
Hi, it worked thank you!

**Comment by OLBITX** [comment]
> Hi, it worked thank you!

Ok!
