### ISSUE TITLE
staking

### ISSUE THREAD

**Issue by Frrosty** [OLBITX/OLBITX#5]
Staking fixed? Does it depend on the number of nodes or the complexity of the network?

**Comment by OLBITX** [comment]
> Staking fixed? Does it depend on the number of nodes or the complexity of the network?

Could you please be more specific about "fixed" word? Staking is working as intended and does not depends on number of nodes. It depends on the coins supply. When number of stable nodes increase the reward for each stable node decreases. This is an intended behavior.

**Comment by MAZIN72** [comment]
Super!

**Comment by Frrosty** [comment]
> > Ставки фиксированы? Зависит ли это от количества узлов или сложности сети?
> 
> Не могли бы вы поконкретнее сказать о «фиксированном» слове? Стейкинг работает по назначению и не зависит от количества узлов. Это зависит от предложения монет. Когда количество стабильных узлов увеличивается, вознаграждение за каждый стабильный узел уменьшается. Это намеренное поведение.

Thanks, that's exactly what I wanted to know.

**Comment by MAZIN72** [comment]
Ok, promising project !!!
--
Отправлено из Mail.ru для Android воскресенье, 20 февраля 2022г., 16:41 +03:00 от Frrosty  ***@***.*** :
